package com.mlhysrszn.periodictable.util

import com.mlhysrszn.periodictable.R
import com.mlhysrszn.periodictable.model.Element
import com.mlhysrszn.periodictable.model.Number

object Utils {

    private val number1 = Number(1)
    private val number2 = Number(2)
    private val number3 = Number(3)
    private val number4 = Number(4)
    private val number5 = Number(5)
    private val number6 = Number(6)
    private val number7 = Number(7)
    private val number8 = Number(8)
    private val number9 = Number(9)
    private val number10 = Number(10)
    private val number11 = Number(11)
    private val number12 = Number(12)
    private val number13 = Number(13)
    private val number14 = Number(14)
    private val number15 = Number(15)
    private val number16 = Number(16)
    private val number17 = Number(17)
    private val number18 = Number(18)

    private val element1 = Element(
        1,
        "H",
        "Hydrogen",
        1.008f,
        R.drawable.bg_nonmetal_color,
        R.color.number_text,
        "aa"
    )

    private val element2 = Element(
        3, "Li", "Lithium", 6.94f, R.color.design_default_color_background,
        R.color.number_text,
    )
    private val element3 = Element(
        11, "Na", "Sodium", 22.989769282f, R.color.design_default_color_background,
        R.color.number_text,
    )
    private val element4 = Element(
        19, "K", "Potassium", 39.09831f, R.color.design_default_color_background,
        R.color.number_text,
    )
    private val element5 = Element(
        37, "Rb", "Rubidium", 85.46783f, R.color.design_default_color_background,
        R.color.number_text,
    )
    private val element6 = Element(
        55, "Cs", "Cesium", 132.905451966f, R.color.design_default_color_background,
        R.color.number_text,
    )
    private val element7 = Element(
        87, "Fr", "Francium", 208.980401f, R.color.design_default_color_background,
        R.color.number_text,
    )
    private val element8 = Element()
    private val element9 = Element()
    private val elementEmpty = Element()

    var list = arrayListOf(
        number1,
        element1,
        element2,
        element3,
        element4,
        element5,
        element6,
        element7,
        elementEmpty,
        element8,
        element9,
        number2,
        element1,
        element1,
        element1,
        element1,
        element1,
        element1,
        element1,
        elementEmpty,
        element1,
        element1,
        number3,
        element1,
        element1,
        element1,
        element1,
        element1,
        element1,
        element1,
        elementEmpty,
        element1,
        element1,
        number4,
        element1,
        element1,
        element1,
        element1,
        element1,
        element1,
        element1,
        elementEmpty,
        element1,
        element1,
        number5,
        element1,
        element1,
        element1,
        element1,
        element1,
        element1,
        element1,
        elementEmpty,
        element1,
        element1,
        number6,
        element1,
        element1,
        element1,
        element1,
        element1,
        element1,
        element1,
        elementEmpty,
        element1,
        element1,
        number7,
        element1,
        element1,
        element1,
        element1,
        element1,
        element1,
        element1,
        elementEmpty,
        element1,
        element1,
        number8,
        element1,
        element1,
        element1,
        element1,
        element1,
        element1,
        element1,
        elementEmpty,
        element1,
        element1,
        number9,
        element1,
        element1,
        element1,
        element1,
        element1,
        element1,
        element1,
        elementEmpty,
        element1,
        element1,
        number10,
        element1,
        element1,
        element1,
        element1,
        element1,
        element1,
        element1,
        elementEmpty,
        element1,
        element1,
        number11,
        element1,
        element1,
        element1,
        element1,
        element1,
        element1,
        element1,
        elementEmpty,
        element1,
        element1,
        number12,
        element1,
        element1,
        element1,
        element1,
        element1,
        element1,
        element1,
        elementEmpty,
        element1,
        element1,
        number13,
        element1,
        element1,
        element1,
        element1,
        element1,
        element1,
        element1,
        elementEmpty,
        element1,
        element1,
        number14,
        element1,
        element1,
        element1,
        element1,
        element1,
        element1,
        element1,
        elementEmpty,
        element1,
        element1,
        number15,
        element1,
        element1,
        element1,
        element1,
        element1,
        element1,
        element1,
        elementEmpty,
        element1,
        element1,
        number16,
        element1,
        element1,
        element1,
        element1,
        element1,
        element1,
        element1,
        elementEmpty,
        element1,
        element1,
        number17,
        element1,
        element1,
        element1,
        element1,
        element1,
        element1,
        element1,
        elementEmpty,
        element1,
        element1,
        number18,
        element1,
        element1,
        element1,
        element1,
        element1,
        element1,
        element1,
        elementEmpty,
        element1,
        element1,
    )
}